### ISSUE TITLE
Oracle jdk license changes

### ISSUE THREAD

**Issue by pang0103** [himgodfreyho/appinventor-docker#1]
Oracle Java downloads now require logging in to an Oracle account to download Java updates.
As a result, this ppa is discontinued.

I am new to docker. Do you have any idea to change the dockerfile to install the openjdk so that the app inventor can run properly ?

Many thanks !

**Comment by himgodfreyho** [comment]
Thanks for pointing out. I have updated the Dockerfile to use openjdk
